'use strict';

const HISTORY_KEY='tracelens.history.v3';
const CASES_KEY='tracelens.cases.v3';
const ACTIVE_CASE_KEY='tracelens.activeCase.v3';
const MAX_HISTORY=30;
const $=(selector,root=document)=>root.querySelector(selector);
const $$=(selector,root=document)=>[...root.querySelectorAll(selector)];
const toolMeta={url:{label:'URL Inspector',icon:'↗'},domain:{label:'Domain Intel',icon:'◎'},ip:{label:'IP Intel',icon:'⌖'},file:{label:'File Intel',icon:'▱'},hash:{label:'Hash Lab',icon:'#'}};
let lastResult=null;

function escapeHtml(value){return String(value??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}
function uid(){return crypto.randomUUID?.()||`${Date.now()}-${Math.random().toString(16).slice(2)}`}
function readJson(key,fallback){try{return JSON.parse(localStorage.getItem(key)||JSON.stringify(fallback))}catch{return fallback}}
function writeJson(key,value){localStorage.setItem(key,JSON.stringify(value))}
function showToast(message){const toast=$('#toast');toast.textContent=message;toast.classList.add('show');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>toast.classList.remove('show'),2200)}
function formatDate(value){return new Intl.DateTimeFormat('nb-NO',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value))}
function formatBytes(bytes){if(!Number.isFinite(bytes)||bytes===0)return'0 B';const units=['B','KB','MB','GB'];const i=Math.min(Math.floor(Math.log(bytes)/Math.log(1024)),units.length-1);return`${(bytes/1024**i).toFixed(i?2:0)} ${units[i]}`}

function setView(name,updateHash=true){const target=$(`#view-${name}`)||$('#view-overview');$$('.view').forEach(view=>view.classList.toggle('active',view===target));$$('.nav-item').forEach(button=>button.classList.toggle('active',button.dataset.view===name));$('#viewTitle').textContent=target.dataset.title;$('#viewEyebrow').textContent=target.dataset.eyebrow;if(updateHash)history.replaceState(null,'',`#${name}`);$('#sidebar').classList.remove('open');window.scrollTo({top:0,behavior:'smooth'})}
function getHistory(){return readJson(HISTORY_KEY,[])}
function saveHistory(type,target,summary){const items=getHistory();items.unshift({id:uid(),type,target,summary,at:new Date().toISOString()});writeJson(HISTORY_KEY,items.slice(0,MAX_HISTORY));renderHistory()}
function renderHistory(){const items=getHistory();$('#analysisCount').textContent=String(items.length);const list=$('#historyList');if(!items.length){list.innerHTML='<div class="history-empty">Ingen analyser ennå</div>';return}list.innerHTML=items.slice(0,10).map(item=>{const meta=toolMeta[item.type]||toolMeta.url;return`<div class="history-item"><span class="history-icon">${meta.icon}</span><div><strong>${escapeHtml(item.target)}</strong><small>${meta.label}${item.summary?` · ${escapeHtml(item.summary)}`:''}</small></div><span class="history-time">${new Date(item.at).toLocaleTimeString('nb-NO',{hour:'2-digit',minute:'2-digit'})}</span></div>`}).join('')}
function setLoading(container,label){container.className='result-area';container.innerHTML=`<div class="loading-state"><span class="loader"></span><span>${escapeHtml(label)}</span></div>`}
function setError(container,title,message){container.className='result-area';container.innerHTML=`<div class="error-panel"><strong>${escapeHtml(title)}</strong><p>${escapeHtml(message)}</p></div>`}
function riskClass(level){return level==='Høy'?'high':level==='Middels'?'medium':'low'}
function resultHeader(target,status='Fullført',level='Lav'){return`<div class="result-header"><div class="result-target"><span>TARGET</span><h2>${escapeHtml(target)}</h2></div><span class="status-pill ${riskClass(level)}">${escapeHtml(status)}</span></div>`}
function dataCard(label,value,wide=false){return`<div class="data-card${wide?' wide':''}"><span class="data-label">${escapeHtml(label)}</span><span class="data-value">${escapeHtml(value||'—')}</span></div>`}
function finding(level,title,text){const cls=level==='high'?'danger':level==='medium'?'warn':'';return`<div class="finding ${cls}"><i></i><div><strong>${escapeHtml(title)}</strong><small>${escapeHtml(text)}</small></div></div>`}
function saveResultButton(){return`<div class="result-actions"><button class="ghost-button" type="button" data-save-result>Lagre i aktiv sak</button></div>`}
function registerResult(type,target,title,summary,data){lastResult={id:uid(),type,target,title,summary,data,createdAt:new Date().toISOString()};saveHistory(type,target,summary)}

function analyzeUrl(raw){let input=raw.trim();if(!input)throw new Error('Lim inn en lenke først.');if(!/^[a-z][a-z0-9+.-]*:/i.test(input))input=`https://${input}`;let url;try{url=new URL(input)}catch{throw new Error('Lenken er ikke gyldig.')}if(!['http:','https:'].includes(url.protocol))throw new Error('Bare HTTP- og HTTPS-lenker støttes.');const findings=[];let score=0;const host=url.hostname.toLowerCase();const suspiciousWords=['login','verify','secure','account','update','password','bank','invoice','payment','wallet','support','confirm'];const ipHost=/^(\d{1,3}\.){3}\d{1,3}$/.test(host)||host.includes(':');if(url.protocol==='http:'){score+=20;findings.push(['medium','Ubeskyttet HTTP','Lenken bruker ikke kryptert HTTPS.'])}if(ipHost){score+=25;findings.push(['high','IP-adresse som vert','Lenken bruker en direkte IP-adresse i stedet for et domenenavn.'])}if(host.includes('xn--')){score+=18;findings.push(['medium','Punycode-domene','Domenet inneholder et internasjonalisert navn som bør kontrolleres nøye.'])}if(raw.includes('@')){score+=25;findings.push(['high','@-tegn i lenken','Tekst før @ kan skjule den faktiske verten.'])}if(url.port&&!['80','443'].includes(url.port)){score+=10;findings.push(['medium','Uvanlig port',`Lenken bruker port ${url.port}.`])}const labels=host.split('.');if(labels.length>4){score+=10;findings.push(['medium','Mange underdomener','En lang kjede av underdomener kan brukes for å skjule hoveddomenet.'])}if(raw.length>150){score+=10;findings.push(['medium','Svært lang lenke','Lange lenker er vanskeligere å kontrollere visuelt.'])}if(/%[0-9a-f]{2}/i.test(raw)){score+=8;findings.push(['medium','Kodede tegn','Lenken inneholder prosentkodede tegn.'])}const keywordHits=suspiciousWords.filter(word=>`${host}${url.pathname}${url.search}`.toLowerCase().includes(word));if(keywordHits.length){score+=Math.min(20,keywordHits.length*5);findings.push(['medium','Sensitive nøkkelord',`Fant: ${keywordHits.join(', ')}.`])}if(url.username||url.password){score+=30;findings.push(['high','Innloggingsdata i URL','Lenken inneholder brukernavn eller passord.'])}score=Math.min(score,100);const level=score>=45?'Høy':score>=20?'Middels':'Lav';if(!findings.length)findings.push(['low','Ingen tydelige strukturelle faresignaler','Dette betyr ikke at nettstedet er garantert trygt.']);return{url,score,level,findings}}
function renderUrlResult(container,raw,analysis){const{url,score,level,findings}=analysis;container.className='result-area';container.innerHTML=resultHeader(url.href,`Risiko ${level}`,level)+saveResultButton()+`<div class="data-grid">${dataCard('Risikoscore',`${score} / 100`)}${dataCard('Protokoll',url.protocol.replace(':','').toUpperCase())}${dataCard('Vert',url.hostname)}${dataCard('Port',url.port||'Standard')}${dataCard('Sti',url.pathname||'/')}${dataCard('Parametere',url.searchParams.size?String(url.searchParams.size):'Ingen')}${dataCard('Normalisert URL',url.href,true)}</div><div class="finding-list">${findings.map(item=>finding(...item)).join('')}</div>`;registerResult('url',url.href,'URL-analyse',`Risiko ${level}`,{score,level,host:url.hostname,protocol:url.protocol,findings})}

function normalizeDomain(value){const input=value.trim().toLowerCase();if(!input)throw new Error('Skriv inn et domene.');try{const url=new URL(input.includes('://')?input:`https://${input}`);const host=url.hostname.replace(/^www\./,'');if(!host.includes('.'))throw new Error();return host}catch{throw new Error('Ugyldig domene. Eksempel: example.com')}}
async function dnsQuery(name,type){const response=await fetch(`https://dns.google/resolve?name=${encodeURIComponent(name)}&type=${encodeURIComponent(type)}`,{headers:{accept:'application/dns-json'}});if(!response.ok)throw new Error(`DNS-tjenesten svarte med ${response.status}.`);return response.json()}
async function analyzeDomain(domain){const queries=[['A',domain],['AAAA',domain],['MX',domain],['NS',domain],['TXT',domain],['CAA',domain],['DMARC',`_dmarc.${domain}`]];const settled=await Promise.allSettled(queries.map(([,name],i)=>dnsQuery(name,queries[i][0]==='DMARC'?'TXT':queries[i][0])));const groups=queries.map(([type],i)=>{const result=settled[i];if(result.status!=='fulfilled')return{type,records:[],error:true};const answers=result.value.Answer||[];return{type,records:answers.filter(a=>a.type!==46).map(a=>({ttl:a.TTL,value:String(a.data||'').replace(/\.$/, '')})),error:false}});const txt=groups.find(g=>g.type==='TXT')?.records.map(r=>r.value).join(' ')||'';const dmarc=groups.find(g=>g.type==='DMARC')?.records.map(r=>r.value).join(' ')||'';const hasSpf=/v=spf1/i.test(txt);const hasDmarc=/v=dmarc1/i.test(dmarc);const hasCaa=(groups.find(g=>g.type==='CAA')?.records.length||0)>0;let score=0;const findings=[];if(!hasSpf){score+=20;findings.push(['medium','SPF ikke funnet','Domenet mangler et synlig SPF-signal i TXT-postene.'])}else findings.push(['low','SPF funnet','Domenet publiserer SPF.']);if(!hasDmarc){score+=25;findings.push(['medium','DMARC ikke funnet','Ingen DMARC-post ble funnet på _dmarc-domenet.'])}else findings.push(['low','DMARC funnet','Domenet publiserer DMARC.']);if(!hasCaa)findings.push(['medium','CAA ikke funnet','Ingen CAA-post ble funnet. Det er ikke nødvendigvis en feil.']);const total=groups.reduce((sum,g)=>sum+g.records.length,0);const level=score>=40?'Høy':score>=20?'Middels':'Lav';return{groups,total,hasSpf,hasDmarc,hasCaa,score,level,findings}}
function renderDomainResult(container,domain,analysis){const populated=analysis.groups.filter(g=>g.records.length);container.className='result-area';container.innerHTML=resultHeader(domain,`Konfigurasjon ${analysis.level}`,analysis.level)+saveResultButton()+`<div class="data-grid">${dataCard('DNS-poster',String(analysis.total))}${dataCard('Posttyper',String(populated.length))}${dataCard('SPF',analysis.hasSpf?'Funnet':'Ikke funnet')}${dataCard('DMARC',analysis.hasDmarc?'Funnet':'Ikke funnet')}${dataCard('CAA',analysis.hasCaa?'Funnet':'Ikke funnet')}${dataCard('IPv4',populated.find(g=>g.type==='A')?.records.map(r=>r.value).join(', ')||'Ingen',true)}</div><div class="finding-list">${analysis.findings.map(item=>finding(...item)).join('')}</div><div class="record-groups">${populated.map(group=>`<div class="record-group"><div class="record-title"><span>${group.type}</span><b>${group.records.length}</b></div>${group.records.map(record=>`<div class="record-row"><small>TTL ${record.ttl}</small><code>${escapeHtml(record.value)}</code></div>`).join('')}</div>`).join('')}</div>`;registerResult('domain',domain,'Domeneanalyse',`${analysis.total} DNS-poster`,analysis)}

function isValidIpv4(value){const parts=value.split('.');return parts.length===4&&parts.every(part=>/^\d{1,3}$/.test(part)&&Number(part)>=0&&Number(part)<=255)}
function isValidIpv6(value){return /^[0-9a-f:]+$/i.test(value)&&value.includes(':')&&value.split(':').length<=8}
function classifyPrivateIp(ip){if(isValidIpv4(ip)){const[a,b]=ip.split('.').map(Number);if(a===10||a===127||(a===192&&b===168)||(a===172&&b>=16&&b<=31)||(a===169&&b===254))return'Privat / lokal IPv4';return null}if(isValidIpv6(ip)){const lower=ip.toLowerCase();if(lower==='::1'||lower.startsWith('fc')||lower.startsWith('fd')||lower.startsWith('fe8')||lower.startsWith('fe9')||lower.startsWith('fea')||lower.startsWith('feb'))return'Privat / lokal IPv6'}return null}
async function lookupIp(ip){const response=await fetch(`https://ipwho.is/${encodeURIComponent(ip)}`);if(!response.ok)throw new Error(`Oppslagstjenesten svarte med ${response.status}.`);const data=await response.json();if(!data.success)throw new Error(data.message||'Fant ikke IP-adressen.');return data}
function renderPrivateIp(container,ip,type){container.className='result-area';container.innerHTML=resultHeader(ip,'Lokal adresse','Lav')+saveResultButton()+`<div class="data-grid">${dataCard('Klassifisering',type)}${dataCard('Eksternt oppslag','Ikke utført')}${dataCard('Betydning','Adressen kan ikke knyttes til en offentlig nettverkseier eller geografisk plassering.',true)}</div>`;registerResult('ip',ip,'IP-analyse',type,{classification:type,public:false})}
function renderIpResult(container,ip,data){const coords=typeof data.latitude==='number'&&typeof data.longitude==='number'?`${data.latitude.toFixed(4)}, ${data.longitude.toFixed(4)}`:'—';container.className='result-area';container.innerHTML=resultHeader(ip,'Offentlig adresse','Lav')+saveResultButton()+`<div class="data-grid">${dataCard('Land',[data.flag?.emoji,data.country].filter(Boolean).join(' '))}${dataCard('By / region',[data.city,data.region].filter(Boolean).join(', '))}${dataCard('ISP',data.connection?.isp)}${dataCard('ASN',data.connection?.asn?`AS${data.connection.asn}`:'—')}${dataCard('Organisasjon',data.connection?.org)}${dataCard('Domene',data.connection?.domain||'—')}${dataCard('Koordinater',coords)}${dataCard('Tidssone',data.timezone?.id||'—')}</div>`;registerResult('ip',ip,'IP-analyse',data.connection?.isp||data.country,{country:data.country,city:data.city,region:data.region,isp:data.connection?.isp,asn:data.connection?.asn,org:data.connection?.org,coordinates:coords})}

async function digest(buffer,algorithm){const hash=await crypto.subtle.digest(algorithm,buffer);return[...new Uint8Array(hash)].map(byte=>byte.toString(16).padStart(2,'0')).join('')}
async function makeHashes(buffer){const[sha256,sha384,sha1]=await Promise.all([digest(buffer,'SHA-256'),digest(buffer,'SHA-384'),digest(buffer,'SHA-1')]);return{sha256,sha384,sha1}}
function detectSignature(bytes){const starts=(...values)=>values.every((value,i)=>bytes[i]===value);if(starts(0x25,0x50,0x44,0x46))return{type:'PDF',mime:'application/pdf',extension:'pdf'};if(starts(0xff,0xd8,0xff))return{type:'JPEG image',mime:'image/jpeg',extension:'jpg'};if(starts(0x89,0x50,0x4e,0x47,0x0d,0x0a,0x1a,0x0a))return{type:'PNG image',mime:'image/png',extension:'png'};if(starts(0x47,0x49,0x46,0x38))return{type:'GIF image',mime:'image/gif',extension:'gif'};if(starts(0x50,0x4b,0x03,0x04))return{type:'ZIP / Office container',mime:'application/zip',extension:'zip'};if(starts(0x4d,0x5a))return{type:'Windows executable',mime:'application/x-msdownload',extension:'exe'};if(starts(0x7f,0x45,0x4c,0x46))return{type:'ELF executable',mime:'application/x-elf',extension:''};return{type:'Ukjent / tekstbasert',mime:'',extension:''}}
function calculateEntropy(bytes){if(!bytes.length)return 0;const counts=new Uint32Array(256);for(const byte of bytes)counts[byte]++;let entropy=0;for(const count of counts){if(!count)continue;const p=count/bytes.length;entropy-=p*Math.log2(p)}return entropy}
async function imageDimensions(file){if(!file.type.startsWith('image/'))return null;const url=URL.createObjectURL(file);try{const img=new Image();return await new Promise((resolve,reject)=>{img.onload=()=>resolve({width:img.naturalWidth,height:img.naturalHeight});img.onerror=reject;img.src=url})}catch{return null}finally{URL.revokeObjectURL(url)}}
function extractPdfMetadata(bytes){const text=new TextDecoder('latin1').decode(bytes.slice(0,Math.min(bytes.length,1024*1024)));const pick=key=>{const match=text.match(new RegExp(`/${key}\\s*\\(([^)]{0,300})\\)`,'i'));return match?.[1]?.replace(/\\([()\\])/g,'$1')||''};return{title:pick('Title'),author:pick('Author'),creator:pick('Creator'),producer:pick('Producer'),created:pick('CreationDate')}}
async function analyzeFile(file){const buffer=await file.arrayBuffer();const bytes=new Uint8Array(buffer);const[hashes,dimensions]=await Promise.all([makeHashes(buffer),imageDimensions(file)]);const signature=detectSignature(bytes);const extension=file.name.includes('.')?file.name.split('.').pop().toLowerCase():'';const extensionMatches=!signature.extension||extension===signature.extension||(signature.extension==='jpg'&&extension==='jpeg')||(signature.extension==='zip'&&['docx','xlsx','pptx','zip'].includes(extension));const pdf=signature.type==='PDF'?extractPdfMetadata(bytes):null;return{hashes,dimensions,signature,extension,extensionMatches,entropy:calculateEntropy(bytes),pdf}}
function renderFileResult(container,file,analysis){const level=analysis.extensionMatches?'Lav':'Høy';const findings=[analysis.extensionMatches?['low','Filtype samsvarer','Filendelsen er forenlig med den oppdagede signaturen.']:['high','Filtypeavvik',`Filendelsen .${analysis.extension||'(ingen)'} samsvarer ikke med signaturen ${analysis.signature.type}.`]];if(analysis.entropy>7.7)findings.push(['medium','Svært høy entropi','Filen kan være komprimert, kryptert eller pakket.']);else findings.push(['low','Entropi målt',`Beregnet til ${analysis.entropy.toFixed(2)} av 8.00.`]);const pdfCards=analysis.pdf?`${dataCard('PDF-tittel',analysis.pdf.title||'—')}${dataCard('PDF-forfatter',analysis.pdf.author||'—')}${dataCard('PDF-produsent',analysis.pdf.producer||'—')}${dataCard('PDF-opprettet',analysis.pdf.created||'—')}`:'';container.className='result-area';container.innerHTML=resultHeader(file.name,analysis.extensionMatches?'Signatur OK':'Filtypeavvik',level)+saveResultButton()+`<div class="data-grid">${dataCard('Oppdaget type',analysis.signature.type)}${dataCard('Nettlesertype',file.type||'Ukjent')}${dataCard('Filstørrelse',formatBytes(file.size))}${dataCard('Sist endret',formatDate(file.lastModified))}${dataCard('Oppløsning',analysis.dimensions?`${analysis.dimensions.width} × ${analysis.dimensions.height}`:'—')}${dataCard('Entropi',`${analysis.entropy.toFixed(2)} / 8.00`)}${pdfCards}${dataCard('SHA-256',analysis.hashes.sha256,true)}</div><div class="finding-list">${findings.map(item=>finding(...item)).join('')}</div>`;registerResult('file',file.name,'Filanalyse',analysis.signature.type,{name:file.name,size:file.size,type:file.type,signature:analysis.signature,extensionMatches:analysis.extensionMatches,entropy:analysis.entropy,dimensions:analysis.dimensions,pdf:analysis.pdf,sha256:analysis.hashes.sha256})}
function renderHashResult(container,target,hashes,size,expected){const normalized=(expected||'').trim().toLowerCase().replace(/\s/g,'');let match=null;if(normalized){match=Object.values(hashes).includes(normalized)}const matchHtml=match===null?'':`<div class="match-banner${match?'':' no'}">${match?'Fingeravtrykket samsvarer med forventet verdi.':'Fingeravtrykket samsvarer ikke med forventet verdi.'}</div>`;container.className='result-area';container.innerHTML=resultHeader(target,match===false?'Avvik funnet':'Fullført',match===false?'Høy':'Lav')+saveResultButton()+matchHtml+`<div class="data-grid">${dataCard('Datamengde',formatBytes(size))}${dataCard('Algoritmer','3')}</div><div class="hash-list">${[['SHA-256',hashes.sha256],['SHA-384',hashes.sha384],['SHA-1',hashes.sha1]].map(([label,value])=>`<div class="hash-row"><span>${label}</span><code>${value}</code><button class="copy-button" type="button" data-copy="${value}" aria-label="Kopier ${label}">⧉</button></div>`).join('')}</div>`;registerResult('hash',target,'Hash-analyse',match===null?'Fingeravtrykk generert':match?'Samsvar':'Avvik',{hashes,expected:normalized,match,size})}

function getCases(){return readJson(CASES_KEY,[])}
function saveCases(cases){writeJson(CASES_KEY,cases);renderCases();renderCaseSelect()}
function getActiveCaseId(){return localStorage.getItem(ACTIVE_CASE_KEY)||''}
function setActiveCase(id){if(id)localStorage.setItem(ACTIVE_CASE_KEY,id);else localStorage.removeItem(ACTIVE_CASE_KEY);renderCases();renderCaseSelect()}
function renderCaseSelect(){const select=$('#activeCaseSelect');const cases=getCases();const active=getActiveCaseId();select.innerHTML='<option value="">Ingen sak</option>'+cases.map(item=>`<option value="${item.id}"${item.id===active?' selected':''}>${escapeHtml(item.title)}</option>`).join('');$('#caseCount').textContent=String(cases.length)}
function renderCases(){const cases=getCases();const active=getActiveCaseId();const list=$('#caseList');if(!cases.length){list.innerHTML='<div class="history-empty">Ingen saker ennå</div>'}else list.innerHTML=cases.map(item=>`<button class="case-item${item.id===active?' active':''}" data-case-id="${item.id}"><strong>${escapeHtml(item.title)}</strong><small>${escapeHtml(item.description||'Ingen beskrivelse')}</small><div class="case-meta"><span>${item.findings.length} funn</span><span>${formatDate(item.updatedAt)}</span></div></button>`).join('');const detail=$('#caseDetail');const item=cases.find(entry=>entry.id===active);if(!item){detail.innerHTML='<div class="empty-state tall"><span>◫</span><p>Velg eller opprett en sak</p></div>';return}detail.innerHTML=`<div class="panel-head"><div><span class="eyebrow">ACTIVE CASE</span><h2>${escapeHtml(item.title)}</h2></div><button class="icon-button" data-delete-case aria-label="Slett sak">×</button></div><p class="case-description">${escapeHtml(item.description||'Ingen beskrivelse')}</p><div class="case-tools"><button class="ghost-button" data-export-json>Eksporter JSON</button><button class="ghost-button" data-export-report>Åpne rapport</button></div><div class="case-notes"><label for="caseNotes">Notater</label><textarea id="caseNotes" rows="5" placeholder="Skriv notater om undersøkelsen">${escapeHtml(item.notes||'')}</textarea></div><div class="section-heading"><div><span class="eyebrow">EVIDENCE</span><h2>Lagrede funn</h2></div></div><div>${item.findings.length?item.findings.map(f=>`<div class="finding-card"><strong>${escapeHtml(f.title)} · ${escapeHtml(f.target)}</strong><small>${escapeHtml(f.summary)} · ${formatDate(f.createdAt)}</small><button class="remove-finding" data-remove-finding="${f.id}" aria-label="Fjern funn">×</button></div>`).join(''):'<div class="history-empty">Ingen funn lagret i saken</div>'}</div>`;$('#caseNotes')?.addEventListener('input',debounce(event=>updateCaseNotes(item.id,event.target.value),300))}
function updateCaseNotes(id,notes){const cases=getCases();const item=cases.find(entry=>entry.id===id);if(!item)return;item.notes=notes;item.updatedAt=new Date().toISOString();writeJson(CASES_KEY,cases);renderCaseSelect()}
function createCase(title,description){const cases=getCases();const now=new Date().toISOString();const item={id:uid(),title:title.trim(),description:description.trim(),notes:'',findings:[],createdAt:now,updatedAt:now};cases.unshift(item);writeJson(CASES_KEY,cases);setActiveCase(item.id);showToast('Sak opprettet')}
function addLastResultToCase(){const id=getActiveCaseId();if(!id){setView('cases');$('#caseDialog').showModal();showToast('Opprett eller velg en sak først');return}if(!lastResult){showToast('Ingen analyse å lagre');return}const cases=getCases();const item=cases.find(entry=>entry.id===id);if(!item){showToast('Aktiv sak finnes ikke');return}item.findings.unshift({...lastResult,id:uid()});item.updatedAt=new Date().toISOString();saveCases(cases);showToast('Funn lagret i saken')}
function removeFinding(id){const active=getActiveCaseId();const cases=getCases();const item=cases.find(entry=>entry.id===active);if(!item)return;item.findings=item.findings.filter(f=>f.id!==id);item.updatedAt=new Date().toISOString();saveCases(cases)}
function deleteActiveCase(){const active=getActiveCaseId();if(!active)return;if(!confirm('Slette denne saken og alle lagrede funn?'))return;saveCases(getCases().filter(item=>item.id!==active));setActiveCase('');showToast('Sak slettet')}
function download(name,content,type){const blob=new Blob([content],{type});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function exportCaseJson(){const item=getCases().find(entry=>entry.id===getActiveCaseId());if(!item)return;download(`tracelens-${slug(item.title)}.json`,JSON.stringify(item,null,2),'application/json')}
function exportCaseReport(){const item=getCases().find(entry=>entry.id===getActiveCaseId());if(!item)return;const rows=item.findings.map(f=>`<article><h3>${escapeHtml(f.title)}</h3><p><b>Mål:</b> ${escapeHtml(f.target)}</p><p><b>Resultat:</b> ${escapeHtml(f.summary)}</p><pre>${escapeHtml(JSON.stringify(f.data,null,2))}</pre></article>`).join('');const html=`<!doctype html><html lang="no"><head><meta charset="utf-8"><title>${escapeHtml(item.title)} – TraceLens</title><style>body{font:15px/1.55 system-ui;max-width:900px;margin:40px auto;padding:0 20px;color:#17202a}header{border-bottom:2px solid #17202a;margin-bottom:28px}small{color:#667}article{border:1px solid #ccd4dc;border-radius:10px;padding:18px;margin:14px 0}pre{white-space:pre-wrap;word-break:break-word;background:#f3f6f8;padding:12px;border-radius:8px}@media print{body{margin:0}}</style></head><body><header><h1>${escapeHtml(item.title)}</h1><p>${escapeHtml(item.description||'')}</p><small>Eksportert ${formatDate(new Date())} · TraceLens</small></header><h2>Notater</h2><p>${escapeHtml(item.notes||'Ingen notater')}</p><h2>Funn (${item.findings.length})</h2>${rows||'<p>Ingen funn.</p>'}</body></html>`;const win=window.open('','_blank');if(!win){showToast('Nettleseren blokkerte rapportvinduet');return}win.document.write(html);win.document.close()}
function slug(value){return value.toLowerCase().replace(/[^a-z0-9æøå]+/gi,'-').replace(/^-|-$/g,'')||'case'}
function debounce(fn,delay){let timer;return(...args)=>{clearTimeout(timer);timer=setTimeout(()=>fn(...args),delay)}}
function wireDropZone(input){const zone=input.closest('.drop-zone');if(!zone)return;['dragenter','dragover'].forEach(name=>zone.addEventListener(name,event=>{event.preventDefault();zone.classList.add('dragover')}));['dragleave','drop'].forEach(name=>zone.addEventListener(name,event=>{event.preventDefault();zone.classList.remove('dragover')}));zone.addEventListener('drop',event=>{const file=event.dataTransfer?.files?.[0];if(!file||typeof DataTransfer==='undefined')return;const dt=new DataTransfer();dt.items.add(file);input.files=dt.files;input.dispatchEvent(new Event('change',{bubbles:true}))})}

$$('.nav-item').forEach(button=>button.addEventListener('click',()=>setView(button.dataset.view)));
$$('[data-open-view]').forEach(button=>button.addEventListener('click',()=>setView(button.dataset.openView)));
$('#menuButton').addEventListener('click',()=>$('#sidebar').classList.toggle('open'));
$('#clearHistoryButton').addEventListener('click',()=>{localStorage.removeItem(HISTORY_KEY);renderHistory();showToast('Historikk slettet')});
$('#activeCaseSelect').addEventListener('change',event=>setActiveCase(event.target.value));

$('#urlForm').addEventListener('submit',event=>{event.preventDefault();const result=$('#urlResult');try{setLoading(result,'ANALYSERER LENKE');const raw=$('#urlInput').value;const analysis=analyzeUrl(raw);renderUrlResult(result,raw,analysis)}catch(error){setError(result,'URL-analysen feilet',error.message)}});
$('#domainForm').addEventListener('submit',async event=>{event.preventDefault();const result=$('#domainResult');const button=event.currentTarget.querySelector('button[type="submit"]');try{const domain=normalizeDomain($('#domainInput').value);button.disabled=true;setLoading(result,'HENTER DNS-DATA');const analysis=await analyzeDomain(domain);renderDomainResult(result,domain,analysis)}catch(error){setError(result,'Domeneoppslaget feilet',`${error.message} Kontroller nettforbindelsen og prøv igjen.`)}finally{button.disabled=false}});
$('#ipForm').addEventListener('submit',async event=>{event.preventDefault();const result=$('#ipResult');const button=event.currentTarget.querySelector('button[type="submit"]');const ip=$('#ipInput').value.trim();if(!isValidIpv4(ip)&&!isValidIpv6(ip)){setError(result,'Ugyldig IP-adresse','Skriv inn en gyldig IPv4- eller IPv6-adresse.');return}const privateType=classifyPrivateIp(ip);if(privateType){renderPrivateIp(result,ip,privateType);return}try{button.disabled=true;setLoading(result,'KARTLEGGER NETTVERK');const data=await lookupIp(ip);renderIpResult(result,ip,data)}catch(error){setError(result,'IP-oppslaget feilet',`${error.message} Kontroller nettforbindelsen og prøv igjen.`)}finally{button.disabled=false}});

$$('[data-hash-mode]').forEach(button=>button.addEventListener('click',()=>{$$('[data-hash-mode]').forEach(item=>item.classList.toggle('active',item===button));const fileMode=button.dataset.hashMode==='file';$('#hashFileMode').hidden=!fileMode;$('#hashTextMode').hidden=fileMode}));
$('#hashFile').addEventListener('change',event=>$('#hashFileName').textContent=event.target.files[0]?.name||'Velg fil');
$('#hashForm').addEventListener('submit',async event=>{event.preventDefault();const result=$('#hashResult');const button=event.currentTarget.querySelector('button[type="submit"]');const fileMode=$('[data-hash-mode="file"]').classList.contains('active');try{let buffer,target;if(fileMode){const file=$('#hashFile').files[0];if(!file)throw new Error('Velg en fil først.');buffer=await file.arrayBuffer();target=file.name}else{const text=$('#hashText').value;if(!text.length)throw new Error('Skriv eller lim inn tekst først.');buffer=new TextEncoder().encode(text);target=`Tekst · ${text.length} tegn`}button.disabled=true;setLoading(result,'BEREGNER FINGERAVTRYKK');const hashes=await makeHashes(buffer);renderHashResult(result,target,hashes,buffer.byteLength,$('#expectedHash').value)}catch(error){setError(result,'Hash-analysen feilet',error.message)}finally{button.disabled=false}});

$('#fileInput').addEventListener('change',event=>$('#fileInputName').textContent=event.target.files[0]?.name||'Slipp en fil her eller trykk for å velge');
$('#fileForm').addEventListener('submit',async event=>{event.preventDefault();const result=$('#fileResult');const button=event.currentTarget.querySelector('button[type="submit"]');const file=$('#fileInput').files[0];if(!file){setError(result,'Ingen fil valgt','Velg en fil før du starter analysen.');return}try{button.disabled=true;setLoading(result,'LESER FILDATA');const analysis=await analyzeFile(file);renderFileResult(result,file,analysis)}catch(error){setError(result,'Filanalysen feilet',error.message)}finally{button.disabled=false}});
wireDropZone($('#fileInput'));wireDropZone($('#hashFile'));

$('#newCaseButton').addEventListener('click',()=>$('#caseDialog').showModal());
$('#caseForm').addEventListener('submit',event=>{if(event.submitter?.value==='cancel')return;event.preventDefault();const title=$('#caseTitle').value.trim();if(!title)return;createCase(title,$('#caseDescription').value);event.currentTarget.reset();$('#caseDialog').close()});
$('#caseList').addEventListener('click',event=>{const item=event.target.closest('[data-case-id]');if(item)setActiveCase(item.dataset.caseId)});
$('#caseDetail').addEventListener('click',event=>{if(event.target.closest('[data-delete-case]'))deleteActiveCase();if(event.target.closest('[data-export-json]'))exportCaseJson();if(event.target.closest('[data-export-report]'))exportCaseReport();const remove=event.target.closest('[data-remove-finding]');if(remove)removeFinding(remove.dataset.removeFinding)});
document.addEventListener('click',async event=>{if(event.target.closest('[data-save-result]'))addLastResultToCase();const copy=event.target.closest('[data-copy]');if(copy){try{await navigator.clipboard.writeText(copy.dataset.copy);showToast('Kopiert')}catch{showToast('Kunne ikke kopiere')}}});

function updateClock(){$('#clock').textContent=new Date().toLocaleTimeString('nb-NO',{hour:'2-digit',minute:'2-digit',second:'2-digit'})}
renderHistory();renderCaseSelect();renderCases();updateClock();setInterval(updateClock,1000);setView(location.hash.slice(1)||'overview',false);
window.addEventListener('hashchange',()=>setView(location.hash.slice(1)||'overview',false));
if('serviceWorker'in navigator&&location.protocol==='https:')window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(error=>console.warn('Service worker:',error)));
